# 端口
server:
  port: 7998
spring:
  application:
    #服务注册名称
    name: system-config
  #读取本地配置文件
  profiles:
    active: native
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true

    config:
      server:
        native:
          search-locations: classpath:/


